require("hova.plugins-setup")
require("hova.core.options")
require("hova.core.keymaps")
require("hova.core.colorscheme")
require("hova.plugins.comment")
require("hova.plugins.nvim-tree")
require("hova.plugins.lualine")
require("hova.plugins.telescope")
require("hova.plugins.nvim-cmp")
require("hova.plugins.lsp.mason")
-- require("hova.plugins.lsp.lspsaga")
require("hova.plugins.lsp.lspconfig")
require("hova.plugins.autopairs")
require("hova.plugins.treesitter")
require("hova.plugins.gitsigns")
